name: Phonebook deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'
    types: [opened, synchronize]

jobs:
  pre_deploy-process:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'
      - name: Install dependencies
        run: npm run install-all
      - name: Check style
        run: npm run lint-all
      - name: Build
        run: npm run build-client
