name: Phonebook deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'
    types: [opened, synchronize]

jobs:
  pre_deploy-process:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'
      - name: Install dependencies
        run: npm run install-all
      - name: Check style
        run: npm run lint-all
      - name: Lint succes
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Linting Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Lint Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Lint Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Lint Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Lint Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build
        run: npm run build-client
  skip_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          SKIP: ${{ contains(toJson(github.event.pull_request.body), '#SKIP') }}
        run: |
          echo "SKIP: $SKIP"
          echo "Conditional: ${{ needs.skip_check.outputs.SKIP !='true' }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        # Only run this step if the branch is master
        if: ${{ needs.skip_check.outputs.SKIP !='true' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          refetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
